# What is Forward Propagation in Neural Networks?
https://www.geeksforgeeks.org/what-is-forward-propagation-in-neural-networks/

In [1]:
import numpy as np
import pandas as pd

# Creating a dataset
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

# Initializing parameters
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    for i in range(1, L):
        parameters['W' + str(i)] = np.ones((layer_dims[i-1], layer_dims[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layer_dims[i], 1))
    return parameters

# Forward propagation
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

def relu(Z):
    return np.maximum(0, Z)

def L_layer_forward(X, parameters):
    A = X
    caches = []
    L = len(parameters) // 2
    for i in range(1, L):
        A_prev = A
        W = parameters['W' + str(i)]
        b = parameters['b' + str(i)]
        Z = linear_forward(A_prev, W, b)
        A = relu(Z)
        cache = (A_prev, W, b, Z)
        caches.append(cache)

    # Output layer
    W_out = parameters['W' + str(L)]
    b_out = parameters['b' + str(L)]
    Z_out = linear_forward(A, W_out, b_out)
    AL = Z_out

    return AL, caches

# Example execution
X = df[['cgpa', 'profile_score']].values[0].reshape(2, 1)
parameters = initialize_parameters([2, 2, 1])
y_hat, caches = L_layer_forward(X, parameters)
print("Final output:")
print(y_hat)

Final output:
[[0.32]]


In [2]:
import numpy as np
import pandas as pd

# Creating a dataset
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [3]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2, 1)
X

array([[8],
       [8]], dtype=int64)

In [4]:
def initialize_parameters(layer_dims):
    print('initialize_parameters')
    print('layer_dims: ' + str(layer_dims))
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    for i in range(1, L):
        parameters['W' + str(i)] = np.ones((layer_dims[i-1], layer_dims[i])) * 0.1
        print(parameters['W' + str(i)] )
        parameters['b' + str(i)] = np.zeros((layer_dims[i], 1))
        print(parameters['b' + str(i)])
    return parameters

In [11]:
def linear_forward(A_prev, W, b):
    print(A_prev)
    print(W)
    print(b)
    Z = np.dot(W.T, A_prev) + b
    return Z

In [6]:
def relu(Z):
    return np.maximum(0, Z)

In [7]:
def L_layer_forward(X, parameters):
    A = X
    caches = []
    L = len(parameters) // 2
    for i in range(1, L):
        print(i)
        A_prev = A
        W = parameters['W' + str(i)]
        b = parameters['b' + str(i)]
        Z = linear_forward(A_prev, W, b)
        print(Z)
        A = relu(Z)
        print(A)
        cache = (A_prev, W, b, Z)
        caches.append(cache)

    # Output layer
    W_out = parameters['W' + str(L)]
    b_out = parameters['b' + str(L)]
    Z_out = linear_forward(A, W_out, b_out)
    AL = Z_out

    return AL, caches

In [12]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2, 1)
X

array([[8],
       [8]], dtype=int64)

In [13]:
parameters = initialize_parameters([2, 2, 1])
parameters

initialize_parameters
layer_dims: [2, 2, 1]
[[0.1 0.1]
 [0.1 0.1]]
[[0.]
 [0.]]
[[0.1]
 [0.1]]
[[0.]]


{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [14]:
y_hat, caches = L_layer_forward(X, parameters)
print("Final output:")
print(y_hat)

1
[[8]
 [8]]
[[0.1 0.1]
 [0.1 0.1]]
[[0.]
 [0.]]


ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)