In [2]:
import numpy as np

W = np.array([
    [1, -3, 5],
    [2, 4, -6]
])
b= np.array([-1, 2, 3])

a_in = np.array([-2, 4])

w = W[:, 0]
print(w)
z = np.dot(w, a_in)
z

[1 2]


6

In [3]:
z = np.dot(a_in, w)
z

6

In [12]:
import numpy as np

X = np.array([
    [10, 20],
    [1, 2]])
W = np.array([[1, -3, 5],
              [-2, 4, -6]])
B = np.array([[-1, 1, 2]])
np.matmul(X, W) + B

array([[-31,  51, -68],
       [ -4,   6,  -5]])

In [1]:
import numpy as np

X = np.array([
    [10, 20],
    [1, 2]])
W = np.array([[1, -3, 5],
              [-2, 4, -6]])
B = np.array([[-1, 1, 2]])
X@W + B

array([[-31,  51, -68],
       [ -4,   6,  -5]])

In [13]:
import numpy as np

X = np.array([
    [10, 20],
    [1, 2]])
W = np.array([[1, -3, 5],
              [-2, 4, -6]])
B = np.array([[-1, 1, 2]])
np.dot(X, W) + B

array([[-31,  51, -68],
       [ -4,   6,  -5]])