In [46]:
import numpy as np

np.random.seed(65)

d3 = np.random.rand(3, 4)
d3

array([[0.21864505, 0.03140272, 0.28712528, 0.17264466],
       [0.30337638, 0.16295022, 0.69931375, 0.77151083],
       [0.51455245, 0.23580689, 0.23003963, 0.50571517]])

In [52]:
keep_prob = 0.6
np.random.seed(65)
d3 = np.random.rand(3, 4) < keep_prob

d3


array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [5]:
import numpy as np

np.random.seed(65)

A1 = np.random.rand(3, 4)
d1 = np.random.rand(A1.shape[0], A1.shape[1])
d1 = (d1 < 0.8).astype(int)
d1

array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])