# numpy.argmin() in Python
https://www.geeksforgeeks.org/numpy-argmin-python/

The numpy.argmin() method returns indices of the min element of the array in a particular axis. 
 

Syntax : 

numpy.argmin(array, axis = None, out = None)

Parameters : 

array : Input array to work on 
axis  : [int, optional]Along a specified axis like 0 or 1
out   : [array optional]Provides a feature to insert output to the out
          array and it should be of appropriate shape and dtype

Return :  

Array of indices into the array with same shape as array.shape
 with the dimension along axis removed.

In [10]:
import numpy as np  
  
# Working on 1D array 
array = np.arange(8) 
print("INPUT ARRAY : \n", array) 
  
  
# returning Indices of the min element 
# as per the indices 
print("\nIndices of min element : ", np.argmin(array, axis=0)) 
print("\nIndices of min element : ", np.argmin(array)) 

INPUT ARRAY : 
 [0 1 2 3 4 5 6 7]

Indices of min element :  0

Indices of min element :  0


In [2]:
print("\nIndices of min element(axis=1) : ", np.argmin(array, axis=1)) 

AxisError: axis 1 is out of bounds for array of dimension 1

In [6]:
import numpy as np  

np.random.seed(25)
  
# Working on 2D array 
array =  np.random.randint(16, size=(4, 4)) 
print("INPUT ARRAY : \n", array) 
  
# returning Indices of the min element 
# as per the indices 
  
'''    
 [[ 4 14 10 15]
  [13  6 15  7]
  [12  2 13  8]
  [12  4  9 13]] 
    ^  ^  ^  ^ 
    4  2  9  7  - element 
    0  2  3  1  - indices 
'''
print("\nIndices of min element : ", np.argmin(array, axis = 0)) 

INPUT ARRAY : 
 [[ 4 14 10 15]
 [13  6 15  7]
 [12  2 13  8]
 [12  4  9 13]]

Indices of min element :  [0 2 3 1]


In [9]:
import numpy as np  

np.random.seed(25)
  
# Working on 2D array 
array =  np.random.randint(16, size=(4, 4)) 
print("INPUT ARRAY : \n", array) 
  
# returning Indices of the min element 
# as per the indices 
  
'''             - element  - indices
 [[ 4 14 10 15] < 4         0
  [13  6 15  7] < 6         1
  [12  2 13  8] < 2         1
  [12  4  9 13]]< 4         1
   
'''
print("\nIndices of min element : ", np.argmin(array, axis = 1)) 

INPUT ARRAY : 
 [[ 4 14 10 15]
 [13  6 15  7]
 [12  2 13  8]
 [12  4  9 13]]

Indices of min element :  [0 1 1 1]


In [15]:
import numpy as np  
  
# Working on 2D array 
array =  np.arange(10).reshape(2, 5) 
print("array : \n", array) 
  
array[0][0] = 10
array[1][1] = 1
array[0][1] = 2
print("\narray : \n", array) 
       
# Returns min element 
print("\narray : ", np.argmin(array)) 
  
# First occurrence of an min element is given 
print("\nmin ELEMENT INDICES : ", np.argmin(array, axis = 0)) 

array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array : 
 [[10  2  2  3  4]
 [ 5  1  7  8  9]]

array :  6

min ELEMENT INDICES :  [1 1 0 0 0]
